version: '3.8'

services:
  # 1. BASE DE DATOS
  db:
    image: postgres:15
    container_name: mi-postgres
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. BACKEND (Spring Boot)
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: